import streamlit as st
import json
import math
import sys
import os

# Ensure the module can be imported
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
try:
    from pgvector_mock import db as pgvector_db
except ImportError:
    # Fallback if module cannot be imported for some reason
    pgvector_db = None

@st.cache_data
def get_historical_context(query):
    """Retrieve historical context using mock pgvector similarity search"""
    if not pgvector_db:
        return ""

    # Very basic mock embedding generator (just arbitrary numbers based on text length)
    # In reality this would be generated by an LLM
    mock_embedding = [len(query)*0.01, len(query)*0.02, -0.1, 0.5]

    results = pgvector_db.search(mock_embedding, limit=1)
    if results:
        doc, score = results[0]
        if score > 0.5: # only return if relatively similar
            return f"\n\n*Historical Context (via pgvector)*: {doc['text']} (Simulated Similarity: {score:.2f})"
    return ""

def inject_custom_css():
    """Injects custom CSS for Glassmorphism UI and Staggered Animations."""
    st.markdown("""
        <style>
        /* Sleek Application Background */
        .stApp {
            background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
        }

        /* Glassmorphism Container Classes */
        .glass-container {
            background: rgba(255, 255, 255, 0.6);
            backdrop-filter: blur(10px);
            -webkit-backdrop-filter: blur(10px);
            border: 1px solid rgba(255, 255, 255, 0.3);
            border-radius: 16px;
            padding: 24px;
            box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.07);
            margin-bottom: 20px;
        }

        /* Framer-like Staggered Fade In Up */
        @keyframes staggerFadeInUp {
            from {
                opacity: 0;
                transform: translateY(30px);
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }

        .stMarkdown, .stTextArea {
            animation: staggerFadeInUp 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards;
        }

        /* Sequential delays for child elements to create stagger effect */
        div[data-testid="stForm"] > div > div:nth-child(1) { animation-delay: 0.1s; }
        div[data-testid="stForm"] > div > div:nth-child(2) { animation-delay: 0.2s; }
        div[data-testid="stForm"] > div > div:nth-child(3) { animation-delay: 0.3s; }
        div[data-testid="stForm"] > div > div:nth-child(4) { animation-delay: 0.4s; }
        div[data-testid="stForm"] > div > div:nth-child(5) { animation-delay: 0.5s; }

        /* Sleek Button Styling (Glassmorphic) */
        .stButton > button {
            background: rgba(255, 255, 255, 0.7);
            border: 1px solid rgba(255, 255, 255, 0.5);
            backdrop-filter: blur(5px);
            border-radius: 8px;
            color: #333;
            font-weight: 600;
            transition: all 0.3s cubic-bezier(0.25, 0.8, 0.25, 1);
            box-shadow: 0 4px 6px rgba(0,0,0,0.05);
        }
        .stButton > button:hover {
            transform: translateY(-2px);
            box-shadow: 0 8px 15px rgba(0,0,0,0.1);
            background: rgba(255, 255, 255, 0.9);
        }
        .stButton > button:active {
            transform: scale(0.97);
        }

        /* Subtle Pulse for QA Alerts (Errors) */
        @keyframes subtlePulse {
            0% { box-shadow: 0 0 0 0 rgba(255, 75, 75, 0.2); }
            50% { box-shadow: 0 0 0 8px rgba(255, 75, 75, 0); }
            100% { box-shadow: 0 0 0 0 rgba(255, 75, 75, 0); }
        }
        div[data-testid="stException"], div[data-testid="stError"] {
            animation: subtlePulse 2.5s infinite;
            border-radius: 12px;
            background: rgba(255, 230, 230, 0.8);
            border: 1px solid rgba(255, 75, 75, 0.2);
        }

        /* Text Area Glassmorphism */
        .stTextArea textarea {
            background: rgba(255, 255, 255, 0.5);
            border: 1px solid rgba(255, 255, 255, 0.8);
            border-radius: 8px;
            transition: all 0.3s ease;
        }
        .stTextArea textarea:focus {
            background: rgba(255, 255, 255, 0.9);
            box-shadow: 0 0 0 3px rgba(100, 150, 255, 0.3);
            border-color: transparent;
        }
        </style>
    """, unsafe_allow_html=True)

@st.cache_data
def mock_ai_extract(text):
    """Simulate AI extraction of structured evidence from raw text, augmented by RAG."""

    historical_context = get_historical_context(text)
    evidence = []

    if "solar" in text.lower() or "panels" in text.lower():
        evidence.append({
            "id": 1,
            "category": "Activity Update",
            "content": "Installed 50 solar panels at the community center." + historical_context,
            "source": "Meeting Notes",
            "confidence": 0.95,
            "reasoning": "Explicit mention of 'solar panels' and 'installed' mapping to Activity Update. Augmented with vector DB search.",
            "approved": False
        })
    if "delay" in text.lower() or "weather" in text.lower():
        evidence.append({
            "id": 2,
            "category": "Risk",
            "content": "Heavy rain causing delays in panel installation.",
            "source": "Meeting Notes",
            "confidence": 0.88,
            "reasoning": "Keywords 'heavy rain' and 'delay' indicate a schedule risk.",
            "approved": False
        })
    if "budget" in text.lower() or "approved" in text.lower() or "funding" in text.lower():
        evidence.append({
            "id": 3,
            "category": "Decision",
            "content": "Additional funding/budget of $5k approved for weatherproofing.",
            "source": "Meeting Notes",
            "confidence": 0.92,
            "reasoning": "Financial figure '$5k' linked with 'approved' denotes a financial decision.",
            "approved": False
        })
    if "water" in text.lower():
         evidence.append({
            "id": 5,
            "category": "Activity Update",
            "content": "Installed new water filtration system.",
            "source": "Meeting Notes",
            "confidence": 0.85,
            "reasoning": "Mention of 'water filtration' implies infrastructure activity.",
            "approved": False
         })

    # New Extractions: Stakeholders and Deadlines
    if "mayor" in text.lower() or "community leaders" in text.lower() or "ngo" in text.lower():
        evidence.append({
            "id": 6,
            "category": "Stakeholder Input",
            "content": "Community leaders and local officials engaged.",
            "source": "Meeting Notes",
            "confidence": 0.89,
            "reasoning": "Identified specific local governance or community representative roles.",
            "approved": False
        })
    if "by next week" in text.lower() or "deadline" in text.lower() or "october" in text.lower():
        evidence.append({
            "id": 7,
            "category": "Deadline",
            "content": "Target completion set for late October.",
            "source": "Meeting Notes",
            "confidence": 0.91,
            "reasoning": "Temporal markers indicating a required timeframe constraint.",
            "approved": False
        })

    if not evidence:
         evidence.append({
            "id": 4,
            "category": "Activity Update",
            "content": "Project kickoff meeting completed.",
            "source": "Meeting Notes",
            "confidence": 0.60,
            "reasoning": "Fallback extraction due to lack of specific domain keywords.",
            "approved": False
        })

    return evidence

def generate_report(evidence_tracker):
    """Generate a donor report draft based ONLY on approved evidence"""
    if not evidence_tracker:
        return "No evidence available to generate report."

    report = "### Donor Report Draft\n\n"
    report += "**Project Activities & Updates:**\n"
    i = 1
    for e in evidence_tracker:
        if e['category'] in ['Activity Update', 'Decision']:
             report += f"{i}. {e['content']}\n"
             i += 1

    report += "\n**Risks & Challenges:**\n"
    i = 1
    for e in evidence_tracker:
        if e['category'] == 'Risk':
             report += f"{i}. {e['content']}\n"
             i += 1

    report += "\n**Stakeholder Engagement & Timelines:**\n"
    i = 1
    for e in evidence_tracker:
        if e['category'] in ['Stakeholder Input', 'Deadline']:
             report += f"{i}. [{e['category']}] {e['content']}\n"
             i += 1

    # Inject a hallucinated claim to demonstrate QA flagging
    report += "\n**Impact:**\n"
    report += "1. Reduced carbon emissions by 500 tons this month. (UNSUPPORTED CLAIM)\n"

    return report

def qa_review(report):
    """Mock QA reviewer that flags unsupported claims"""
    flags = []
    if "UNSUPPORTED CLAIM" in report:
        flags.append({
            "type": "Unsupported Claim / Overclaiming",
            "description": "The claim 'Reduced carbon emissions by 500 tons this month' is not supported by the approved evidence tracker."
        })
    return flags

def main():
    st.set_page_config(page_title="CLEAR Climate Copilot", layout="wide")

    # Inject animations and glassmorphism UI
    inject_custom_css()

    st.title("CLEAR Climate Copilot")
    st.subheader("Turn scattered project information into structured reporting evidence")

    st.sidebar.title("Workflow")
    st.sidebar.markdown("""
    1. Input Notes
    2. Extract & Edit Evidence
    3. Review & Approve
    4. Generate Draft Report
    5. QA Review
    6. Export
    """)

    # Initialize session state
    if 'evidence_tracker' not in st.session_state:
        st.session_state['evidence_tracker'] = []
    if 'draft_report' not in st.session_state:
        st.session_state['draft_report'] = None
    if 'qa_flags' not in st.session_state:
         st.session_state['qa_flags'] = []
    if 'extracted_evidence' not in st.session_state:
        st.session_state['extracted_evidence'] = []

    st.markdown('<div class="glass-container">', unsafe_allow_html=True)
    st.header("Step 1: Input Meeting Notes or Updates")
    notes_input = st.text_area("Paste meeting notes, activity updates, or stakeholder inputs here:", height=150)

    if st.button("Process Notes"):
        if notes_input.strip() == "":
            st.warning("Please enter some notes to process.")
        else:
            st.session_state['notes_processed'] = True
            # Load new evidence, resetting edits
            st.session_state['extracted_evidence'] = mock_ai_extract(notes_input)
            st.success("Notes processed! See extracted evidence below.")
    st.markdown('</div>', unsafe_allow_html=True)

    if st.session_state.get('notes_processed'):
        st.markdown('<div class="glass-container">', unsafe_allow_html=True)
        st.header("Step 2 & 3: AI Extraction, Edit & Human Approval")
        st.markdown("Review and edit the extracted evidence. **AI output must be treated as draft output, not truth.** Human approval is required before evidence enters the tracker.")

        extracted = st.session_state.get('extracted_evidence', [])

        if not extracted:
             st.info("No evidence extracted.")
        else:
            with st.form("approval_form"):
                approved_ids = []
                # We need to keep track of edited content before submission
                edited_content_map = {}

                for i, item in enumerate(extracted):
                    col1, col2 = st.columns([1, 4])

                    with col1:
                        st.write(f"**{item['category']}**")
                        # Display confidence score with color coding
                        conf = item.get('confidence', 0)
                        color = "green" if conf > 0.8 else ("orange" if conf > 0.5 else "red")
                        st.markdown(f"AI Confidence: :{color}[{conf*100:.0f}%]")
                        st.markdown(f"*(AI Reasoning: {item.get('reasoning', 'N/A')})*")

                        is_approved = st.checkbox("Approve", key=f"approve_{item['id']}")
                        if is_approved:
                            approved_ids.append(item['id'])

                    with col2:
                        # Allow user to edit the AI's drafted content
                        edited_content = st.text_area(
                            "Edit Content:",
                            value=item['content'],
                            key=f"edit_content_{item['id']}",
                            height=85
                        )
                        edited_content_map[item['id']] = edited_content

                    st.markdown("---")

                submitted = st.form_submit_button("Save Approved Evidence to Tracker")

                if submitted:
                    for item in extracted:
                        # Update the item with whatever the user edited
                        item['content'] = edited_content_map[item['id']]

                        if item['id'] in approved_ids:
                            # Avoid duplicates in tracker
                            if not any(e['id'] == item['id'] for e in st.session_state['evidence_tracker']):
                                item['approved'] = True
                                # Add a copy to the tracker
                                st.session_state['evidence_tracker'].append(dict(item))

                    if approved_ids:
                        st.success(f"Saved {len(approved_ids)} items to Evidence Tracker!")
                    else:
                        st.warning("No items selected for approval.")
        st.markdown('</div>', unsafe_allow_html=True)

        if st.session_state['evidence_tracker']:
            st.markdown('<div class="glass-container">', unsafe_allow_html=True)
            st.header("Evidence Tracker")
            for e in st.session_state['evidence_tracker']:
                st.write(f"- [{e['category']}] {e['content']}")

            col_clear, col_json = st.columns(2)
            with col_clear:
                if st.button("Clear Evidence Tracker"):
                    st.session_state['evidence_tracker'] = []
                    st.session_state['draft_report'] = None
                    st.rerun()
            with col_json:
                tracker_json = json.dumps(st.session_state['evidence_tracker'], indent=2)
                st.download_button(
                    label="Download Tracker Data (JSON)",
                    data=tracker_json,
                    file_name="evidence_tracker.json",
                    mime="application/json"
                )
            st.markdown('</div>', unsafe_allow_html=True)

            st.markdown('<div class="glass-container">', unsafe_allow_html=True)
            st.header("Step 4 & 5: Report Generation & QA")
            if st.button("Generate Donor Report Draft"):
                report = generate_report(st.session_state['evidence_tracker'])
                flags = qa_review(report)

                st.session_state['draft_report'] = report
                st.session_state['qa_flags'] = flags

            if st.session_state.get('draft_report'):
                st.markdown(st.session_state['draft_report'])

                if st.session_state.get('qa_flags'):
                     st.error("### QA Review Alerts")
                     for flag in st.session_state['qa_flags']:
                         st.write(f"**{flag['type']}**: {flag['description']}")
                else:
                     st.success("QA Review Passed: No unsupported claims found.")

                st.divider()
                st.header("Step 6: Export")
                st.download_button(
                    label="Download Report as TXT",
                    data=st.session_state['draft_report'],
                    file_name="donor_report_draft.txt",
                    mime="text/plain"
                )
            st.markdown('</div>', unsafe_allow_html=True)

if __name__ == "__main__":
    main()


# --- Vercel WSGI Handler ---
# To satisfy the `@vercel/python` builder, we provide a top-level `app` WSGI callable.
def app(environ, start_response):
    status = '200 OK'
    headers = [('Content-type', 'text/plain; charset=utf-8')]
    start_response(status, headers)
    return [b"Streamlit App Deployment. Note: Streamlit requires WebSockets which are not supported by Vercel Serverless Functions."]
